title:              SDE Skills
email:              website@sdeskills.com
description:        Get upgraded of get deprecated!
author:             Vivek K
baseurl:            ""
url:                "http://beta.sdeskills.com"

# Social Profiles
twitter_username:   sdeskills
github_username:    sde-skills
facebook_username:  sdeskills
linkedin_username:  sdeskills

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-redirect-from

# Team names, titles and social links
team:
- name: Bhavesh Patel
  pic: bhavesh.jpg
  position: President / Executive Director
  intro: 

- name: Devi Nayar
  pic: devi.jpg
  position: Seattle Chapter Lead 
  intro: Accomplished software engineer with experience in developing and maintaining complex software solutions for large international corporations in banking, telecommunications and health care industries.

- name: Gaurav Agarwal
  pic: gaurav.jpg
  position: Seattle Tech Lead
  intro: Senior Software Engineer at Microsoft with over 12 years of experience in Software Development.

- name: Supriya Dixit
  pic: placeholder.jpg
  position: Seattle Operations Lead
  intro: An experienced program manager and software developer with over 6 years of experience. Active volunteer at several local non-profits.

- name: Sanath Kumar
  pic: sanath.jpg
  position: Bay Area Chapter Lead
  intro: Softaware Development Engineer at NGINX with a passion for solving tough, challenging problems. Passionate about building products, services, solutions to make customers, engineers life better. Enjoys working on products, infrastructure which drive customer value.

advisors:
- name: Vivek Kirubanandan
  pic: vivek.jpg
  position: Founder and Advisor
  intro: An experienced Engineering Leader with expertise in building and leading multiple engineering teams of Software Development Engineers and Engineering Managers.

