title:              SDE Skills
email:              website@sdeskills.com
description:        Get upgraded of get deprecated!
author:             Vivek K
baseurl:            "/beta"
url:                "http://beta.sdeskills.com"

# Social Profiles
twitter_username:   sdeskills
github_username:    sde-skills
facebook_username:  sdeskills
linkedin_username:  sdeskills

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-redirect-from

collections:
  chapters:
    output: true
    permalink: /chapters/:path
